### ISSUE TITLE
Getting 500 when trying to push a new gem

### ISSUE THREAD

**Issue by rwz** [heroku/gemgate#1]
Trying to push a new gem:

``` sh
$ curl -f -u "gemgate:REDACTED" -F "file=@umbrella-auth-0.0.1.gem" https://gemgate-heroku-internal-gems.herokuapp.com
```

And getting 500.

Here's the app log:

```
2015-05-21T16:00:09.819933+00:00 heroku[router]: at=info method=POST path="/" host=gemgate-heroku-internal-gems.herokuapp.com request_id=75b9ae44-cb51-4a84-9feb-58e6972bb530 fwd="73.223.134.129" dyno=web.1 connect=1ms service=3855ms status=500 bytes=253
2015-05-21T16:00:09.811629+00:00 app[web.1]: NameError - uninitialized constant Gem::Package:
2015-05-21T16:00:09.811652+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `block (3 levels) in route!'
2015-05-21T16:00:09.811636+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/gemgate-0.0.1/lib/gemgate/gem_wrapper.rb:5:in `block in from_path'
2015-05-21T16:00:09.811649+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `block in compile!'
2015-05-21T16:00:09.811656+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:822:in `block in process_route'
2015-05-21T16:00:09.811657+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `catch'
2015-05-21T16:00:09.811661+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `each'
2015-05-21T16:00:09.811640+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/gemgate-0.0.1/lib/gemgate/gem_wrapper.rb:4:in `tap'
2015-05-21T16:00:09.811646+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/gemgate-0.0.1/lib/gemgate/web.rb:29:in `block in <class:Web>'
2015-05-21T16:00:09.811659+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:820:in `process_route'
2015-05-21T16:00:09.811641+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/gemgate-0.0.1/lib/gemgate/gem_wrapper.rb:4:in `from_path'
2015-05-21T16:00:09.811645+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/gemgate-0.0.1/lib/gemgate/repository.rb:6:in `add_gem'
2015-05-21T16:00:09.811663+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:886:in `dispatch!'
2015-05-21T16:00:09.811643+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/gemgate-0.0.1/lib/gemgate/repository.rb:6:in `call'
2015-05-21T16:00:09.811653+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:801:in `route_eval'
2015-05-21T16:00:09.811648+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:1212:in `call'
2015-05-21T16:00:09.811655+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `block (2 levels) in route!'
2015-05-21T16:00:09.811650+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `[]'
2015-05-21T16:00:09.811669+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `invoke'
2015-05-21T16:00:09.811660+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:784:in `block in route!'
2015-05-21T16:00:09.811671+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:705:in `call'
2015-05-21T16:00:09.811662+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:783:in `route!'
2015-05-21T16:00:09.811665+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `block in call!'
2015-05-21T16:00:09.811674+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
2015-05-21T16:00:09.811667+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `catch'
2015-05-21T16:00:09.811666+00:00 app[we
b.1]:   /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:871:in `block in invoke'
2015-05-21T16:00:09.811673+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/lib/rack/auth/basic.rb:25:in `call'
2015-05-21T16:00:09.811670+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:719:in `call!'
2015-05-21T16:00:09.811676+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
2015-05-21T16:00:09.811682+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/lib/rack/head.rb:9:in `call'
2015-05-21T16:00:09.811684+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `block in call'
2015-05-21T16:00:09.811677+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
2015-05-21T16:00:09.811681+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/lib/rack/nulllogger.rb:9:in `call'
2015-05-21T16:00:09.811680+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
2015-05-21T16:00:09.811686+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `call'
2015-05-21T16:00:09.811685+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/sinatra-1.3.2/lib/sinatra/base.rb:1416:in `synchronize'
2015-05-21T16:00:09.811678+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
2015-05-21T16:00:09.811689+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/lib/rack/urlmap.rb:49:in `each'
2015-05-21T16:00:09.811687+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/lib/rack/urlmap.rb:64:in `block in call'
2015-05-21T16:00:09.811690+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/lib/rack/urlmap.rb:49:in `call'
2015-05-21T16:00:09.811691+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/thin-1.2.11/lib/thin/connection.rb:84:in `block in pre_process'
2015-05-21T16:00:09.811694+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/thin-1.2.11/lib/thin/connection.rb:82:in `pre_process'
2015-05-21T16:00:09.811692+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/thin-1.2.11/lib/thin/connection.rb:82:in `catch'
2015-05-21T16:00:09.811695+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/thin-1.2.11/lib/thin/connection.rb:57:in `process'
2015-05-21T16:00:09.811696+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/thin-1.2.11/lib/thin/connection.rb:42:in `receive_data'
2015-05-21T16:00:09.811707+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
2015-05-21T16:00:09.811705+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
2015-05-21T16:00:09.811708+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/thin-1.2.11/lib/thin/backends/base.rb:61:in `start'
2015-05-21T16:00:09.811709+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/thin-1.2.11/lib/thin/server.rb:159:in `start'
2015-05-21T16:00:09.811710+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/lib/rack/handler/thin.rb:13:in `run'
2015-05-21T16:00:09.811712+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/lib/rack/server.rb:265:in `start'
2015-05-21T16:00:09.811714+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/lib/rack/server.rb:137:in `start'
2015-05-21T16:00:09.811715+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/gems/rack-1.4.1/bin/rackup:4:in `<top (required)>'
2015-05-21T16:00:09.811716+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `load'
2015-05-21T16:00:09.811718+00:00 app[web.1]:    /app/vendor/bundle/ruby/2.0.0/bin/rackup:23:in `<main>'
```

**Comment by dmathieu** [comment]
I saw the same problem.
